export const mockPatientData = {
  patients: [
    {
      id: "1",
      name: "Amit Rao",
      email: "amit.rao@example.com",
      age: 29,
      gender: "Male",
      phone: "+91-9876543210",
      recentActivity: [
        {
          title: "Symptom Report Submitted",
          date: "2024-01-15",
          type: "report",
        },
        {
          title: "Video Consultation with Dr. Ananya Mehta",
          date: "2024-01-12",
          type: "appointment",
        },
        {
          title: "Lab Results Available",
          date: "2024-01-10",
          type: "lab",
        },
      ],
      upcomingAppointments: [
        {
          id: "1",
          doctor: "Dr. Ananya Mehta",
          specialty: "General Medicine",
          date: "2024-01-20",
          time: "2:00 PM",
          type: "video",
        },
        {
          id: "2",
          doctor: "Dr. Arjun Kapoor",
          specialty: "Cardiology",
          date: "2024-01-25",
          time: "10:30 AM",
          type: "in-person",
        },
      ],
    },
  ],
  medicalRecords: [
    {
      id: "1",
      title: "Annual Health Checkup",
      description:
        "Comprehensive health check including CBC, thyroid panel, and vitals",
      date: "2024-01-15",
      doctor: "Dr. Ananya Mehta",
      type: "visit",
    },
    {
      id: "2",
      title: "Viral Fever Diagnosis",
      description:
        "AI-assisted diagnosis based on reported symptoms and clinical review",
      date: "2024-01-12",
      doctor: "AI Assistant",
      type: "diagnosis",
    },
    {
      id: "3",
      title: "Blood Pressure Medication",
      description: "Prescribed Telmisartan 40mg daily for hypertension",
      date: "2024-01-10",
      doctor: "Dr. Arjun Kapoor",
      type: "prescription",
    },
    {
      id: "4",
      title: "Complete Blood Count (CBC)",
      description: "Normal blood cell counts and no abnormalities detected",
      date: "2024-01-08",
      doctor: "Lab Technician",
      type: "lab",
    },
    {
      id: "5",
      title: "Chest X-Ray Results",
      description: "Clear X-ray, no pulmonary issues observed",
      date: "2024-01-05",
      doctor: "Dr. Neha Menon",
      type: "lab",
    },
  ],
};

export const mockDoctorData = {
  doctors: [
    {
      id: "1",
      name: "Dr. Ananya Mehta",
      specialty: "General Medicine",
      email: "dr.ananya@hospitalindia.com",
      totalPatients: 142,
      todayAppointments: 7,
      pendingReviews: 10,
      patients: [
        {
          id: "1",
          name: "Sri-Hasnika",
          condition: "Viral Fever",
          urgency: "low",
          lastVisit: "2024-01-12",
          nextAppointment: "2024-01-20",
        },
        {
          id: "2",
          name: "Priya Nair",
          condition: "Hypertension Follow-up",
          urgency: "medium",
          lastVisit: "2024-01-10",
          nextAppointment: "2024-01-18",
        },
        {
          id: "3",
          name: "Rahul Sharma",
          condition: "Chest Pain Evaluation",
          urgency: "high",
          lastVisit: "2024-01-15",
          nextAppointment: "Today",
        },
        {
          id: "4",
          name: "Sneha Reddy",
          condition: "Diabetes Management",
          urgency: "medium",
          lastVisit: "2024-01-08",
          nextAppointment: "2024-01-22",
        },
      ],

      todaySchedule: [
        {
          time: "9:00 AM",
          patient: "Rahul Sharma",
          type: "Emergency Consultation",
          status: "upcoming",
        },
        {
          time: "10:30 AM",
          patient: "Meera Iyer",
          type: "Follow-up Visit",
          status: "completed",
        },
        {
          time: "2:00 PM",
          patient: "Amit Rao",
          type: "Video Consultation",
          status: "upcoming",
        },
        {
          time: "3:30 PM",
          patient: "Priya Nair",
          type: "Routine Checkup",
          status: "upcoming",
        },
      ],
    },
  ],
};

export const mockChatData = {
  messages: [
    {
      id: "1",
      content:
        "Namaste! I'm your AI health assistant. How may I assist you today?",
      sender: "ai",
      timestamp: "9:00 AM",
      type: "text",
    },
    {
      id: "2",
      content:
        "I've been having a headache for two days. Should I be worried?",
      sender: "user",
      timestamp: "9:02 AM",
      type: "text",
    },
    {
      id: "3",
      content:
        "I understand you're experiencing headaches. Is it constant or does it come and go? Please rate the pain 1-10.",
      sender: "ai",
      timestamp: "9:02 AM",
      type: "text",
    },
    {
      id: "4",
      content: "It's around 6/10, mostly in the morning.",
      sender: "user",
      timestamp: "9:05 AM",
      type: "text",
    },
    {
      id: "5",
      content: "Dr. Ananya Mehta has joined the chat.",
      sender: "system",
      timestamp: "9:10 AM",
      type: "system",
    },
    {
      id: "6",
      content:
        "Hi Amit. Based on your symptoms, this could be a tension headache. Let's schedule a call to discuss further.",
      sender: "doctor",
      timestamp: "9:12 AM",
      type: "text",
    },
  ],
};

export const mockAppointmentData = {
  patientAppointments: [
    {
      id: "1",
      doctor: "Dr. Ananya Mehta",
      specialty: "General Medicine",
      date: "2024-01-20",
      time: "2:00 PM",
      type: "video",
      status: "confirmed",
      reason: "Follow-up after fever",
      location: null,
    },
    {
      id: "2",
      doctor: "Dr. Arjun Kapoor",
      specialty: "Cardiology",
      date: "2024-01-25",
      time: "10:30 AM",
      type: "in-person",
      status: "confirmed",
      reason: "Blood pressure management review",
      location: "Cardiology Dept., Fortis Hospital",
    },
    {
      id: "3",
      doctor: "Dr. Neha Menon",
      specialty: "Dermatology",
      date: "2024-01-18",
      time: "3:00 PM",
      type: "video",
      status: "pending",
      reason: "Skin rash consultation",
      location: null,
    },
    {
      id: "4",
      doctor: "Dr. Rohan Singh",
      specialty: "Orthopedics",
      date: "2024-01-15",
      time: "11:00 AM",
      type: "in-person",
      status: "completed",
      reason: "Knee pain evaluation",
      location: "Ortho Clinic, Max Healthcare",
    },
    {
      id: "5",
      doctor: "Dr. Kavya Rao",
      specialty: "Psychiatry",
      date: "2024-01-22",
      time: "4:30 PM",
      type: "phone",
      status: "confirmed",
      reason: "Anxiety follow-up",
      location: null,
    },
    {
      id: "6",
      doctor: "Dr. Ananya Mehta",
      specialty: "General Medicine",
      date: "2024-01-12",
      time: "1:00 PM",
      type: "video",
      status: "cancelled",
      reason: "General consultation",
      location: null,
    },
  ],

  doctorAppointments: [
    {
      id: "1",
      patient: "Amit Rao",
      date: "2024-01-20",
      time: "2:00 PM",
      type: "video",
      status: "confirmed",
      reason: "Follow-up after fever",
      notes: "Improvement reported",
    },
    {
      id: "2",
      patient: "Priya Nair",
      date: "2024-01-18",
      time: "10:00 AM",
      type: "in-person",
      status: "pending",
      reason: "Hypertension review",
      notes: "New patient, full assessment needed",
    },
    {
      id: "3",
      patient: "Rahul Sharma",
      date: new Date().toISOString().split("T")[0],
      time: "9:00 AM",
      type: "video",
      status: "confirmed",
      reason: "Chest pain evaluation",
      notes: "Urgent case",
    },
    {
      id: "4",
      patient: "Sneha Reddy",
      date: new Date().toISOString().split("T")[0],
      time: "11:30 AM",
      type: "phone",
      status: "confirmed",
      reason: "Diabetes management",
      notes: "Monthly review",
    },
    {
      id: "5",
      patient: "Vikram Gupta",
      date: "2024-01-19",
      time: "3:30 PM",
      type: "in-person",
      status: "pending",
      reason: "Annual checkup",
      notes: "First visit",
    },
    {
      id: "6",
      patient: "Ayesha Khan",
      date: new Date().toISOString().split("T")[0],
      time: "2:30 PM",
      type: "video",
      status: "completed",
      reason: "Medication side-effects",
      notes: "Mild symptoms reported",
    },
    {
      id: "7",
      patient: "Karthik Rao",
      date: "2024-01-21",
      time: "4:00 PM",
      type: "video",
      status: "confirmed",
      reason: "Mental health follow-up",
      notes: "Anxiety management",
    },
    {
      id: "8",
      patient: "Divya Sharma",
      date: "2024-01-17",
      time: "1:30 PM",
      type: "phone",
      status: "pending",
      reason: "Medication refill",
      notes: "Prescription renewal",
    },
  ],
};
